/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        "outline-variant": "#424754",
        "primary": "#adc6ff",
        "on-surface-variant": "#c2c6d6",
        "primary-fixed": "#d8e2ff",
        "surface-container": "#191f2f",
        "inverse-surface": "#dde2f8",
        "surface-container-highest": "#2f3445",
        "outline": "#8c909f",
        "secondary-container": "#e3aa00",
        "inverse-primary": "#005ac2",
        "secondary-fixed": "#ffdf9f",
        "on-error": "#690005",
        "on-surface": "#dde2f8",
        "on-background": "#dde2f8",
        "tertiary-fixed": "#6ffbbe",
        "on-secondary-fixed-variant": "#5c4300",
        "error": "#ffb4ab",
        "on-secondary": "#402d00",
        "surface": "#0d1322",
        "on-tertiary-fixed-variant": "#005236",
        "on-primary-container": "#00285d",
        "secondary-fixed-dim": "#f9bd22",
        "on-error-container": "#ffdad6",
        "surface-container-lowest": "#080e1d",
        "primary-fixed-dim": "#adc6ff",
        "tertiary-container": "#00a572",
        "on-tertiary-container": "#00311f",
        "surface-container-low": "#151b2b",
        "surface-variant": "#2f3445",
        "surface-container-high": "#242a3a",
        "surface-bright": "#33394a",
        "tertiary-fixed-dim": "#4edea3",
        "on-tertiary": "#003824",
        "on-primary": "#002e6a",
        "on-primary-fixed-variant": "#004395",
        "tertiary": "#4edea3",
        "on-secondary-fixed": "#261a00",
        "primary-container": "#4d8eff",
        "surface-dim": "#0d1322",
        "inverse-on-surface": "#2a3040",
        "background": "#0d1322",
        "surface-tint": "#adc6ff",
        "on-secondary-container": "#5a4100",
        "on-tertiary-fixed": "#002113",
        "error-container": "#93000a",
        "on-primary-fixed": "#001a42",
        "secondary": "#ffc640"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "container-max": "1280px",
        "margin-desktop": "32px",
        "stack-sm": "8px",
        "margin-mobile": "16px",
        "gutter": "24px",
        "stack-md": "16px",
        "stack-lg": "32px"
      },
      fontFamily: {
        "stats-xl": ["Montserrat", "sans-serif"],
        "display-lg": ["Montserrat", "sans-serif"],
        "headline-lg-mobile": ["Montserrat", "sans-serif"],
        "display-lg-mobile": ["Montserrat", "sans-serif"],
        "headline-md": ["Montserrat", "sans-serif"],
        "headline-lg": ["Montserrat", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"]
      },
    }
  },
  plugins: [],
}
